# Generated by Django 4.1.5 on 2023-01-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_party', '0001_initial'),
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='third_party.customer'),
        ),
    ]
