# Generated by Django 4.1.5 on 2023-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_alter_salesitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='disc_percent',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax_percent',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
