# Generated by Django 4.1.5 on 2023-01-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_alter_sales_disc_percent_alter_sales_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='sales',
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_items',
            field=models.ManyToManyField(to='sales_app.salesitem'),
        ),
    ]
