# Generated by Django 4.1.5 on 2023-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_remove_salesitem_sales_sales_sales_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invoice_number',
            field=models.CharField(blank=True, default='SAL-1500', max_length=10, null=True),
        ),
    ]
