# Generated by Django 4.1.5 on 2023-04-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0007_sales_sales_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('-created_at',)},
        ),
    ]
