# Generated by Django 4.1.5 on 2023-01-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_at',)},
        ),
    ]
