# Generated by Django 4.1.5 on 2023-01-17 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
