# Generated by Django 4.1.5 on 2023-01-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_rename_price_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='1000', max_length=50, unique=True),
        ),
    ]
