# Generated by Django 4.1.5 on 2023-01-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1000, max_length=50, unique=True),
        ),
    ]
