# Generated by Django 4.1.5 on 2023-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/home/commando/PycharmProjects/Inventory Management System(CLZ)/media/images/f-35.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
