# Generated by Django 4.1.5 on 2023-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1000, max_length=50, null=True, unique=True),
        ),
    ]
