# Generated by Django 4.1.5 on 2023-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
