# Generated by Django 4.1.5 on 2023-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0002_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
