# Generated by Django 4.1.5 on 2023-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_alter_purchaseitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
