# Generated by Django 4.1.5 on 2023-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0004_alter_purchase_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_items',
            field=models.ManyToManyField(to='purchase_app.purchaseitem'),
        ),
    ]
