# Generated by Django 4.1.5 on 2023-01-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0005_remove_purchaseitem_purchase_purchase_purchase_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='disc_percent',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_percent',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
