# Generated by Django 4.1.5 on 2023-01-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0006_alter_purchase_disc_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_number',
            field=models.CharField(blank=True, default='PUR-1500', max_length=10, null=True),
        ),
    ]
