# Generated by Django 4.1.5 on 2023-02-08 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_app', '0007_purchase_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='myuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
