# Generated by Django 4.1.5 on 2023-02-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0008_purchase_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='myuser',
            new_name='done_by',
        ),
    ]
